### ISSUE TITLE
Improve deletebyname Command Parser

### ISSUE THREAD

**Issue by dezhanglee** [CS2103JAN2018-T15-B4/main#78]
From @esilocke
"Try running deletebyname as it is, or deletebyname 1, does it work as expected?"

Should be able to fix this by using the multimap method used in other parsers :)

**Comment by dezhanglee** [comment]
Can't seem to find any bug? @x3tsunayh @jill858 @CYX28 any thoughts, before I close this?

**Comment by x3tsunayh** [comment]
I can't reproduce the said bug either.

**Comment by dezhanglee** [comment]
I shall close this. Can reopen next time if we are able to reproduce it.
